# -*- coding: utf-8 -*-
"""PizzaGlobalAIHub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-u3sizp66JmBVIGiqlyEdV4oAEVNrDV
"""

import csv
import datetime

class Pizza:
    def __init__(self, description, cost):
        self.__description = description
        self.__cost = cost
    
    def get_description(self):
        return self.__description
    
    def get_cost(self):
        return self.__cost

class Klasik(Pizza):
    def __init__(self):
        super().__init__("Klasik Pizza:  domates, peynir ve genellikle çeşitli diğer malzemelerle  yenen bir yemektir.", 20)

class Margarita(Pizza):
    def __init__(self):
        super().__init__("Margarita Pizza: domates, mozarella, fesleğen, zeytinyağı ve tuzla yapılan Napoli pizzasıdır.", 25)

class TurkPizza(Pizza):
    def __init__(self):
        super().__init__("Türk Pizza:  sucuk, pastırma, biber, ve mantar ile yapılan pizzadır.", 30)

class SadePizza(Pizza):
    def __init__(self):
        super().__init__("Sade Pizza: pizza hamuru, mozzarella peyniri ve domates ile yapılan pizzadır.", 15)

class Decorator():
    def __init__(self, description, cost):
        self.__description = description
        self.__cost = cost

    def get_description(self):
        return self.__description
    
    def get_cost(self):
        return self.__cost

class Zeytin(Decorator):
    def __init__(self):
        super().__init__("Zeytin",3)


class Mantar(Decorator):
    def __init__(self):
        super().__init__("Mantarlar",2)
      

class KeciPeyniri(Decorator):
    def __init__(self):
        super().__init__("Keçi Peyniri",5)
        

class Et(Decorator):
    def __init__(self):
        super().__init__("Et",4)
      

class Sogan(Decorator):
    def __init__(self):
        super().__init__("Soğan",1)
       

class Misir(Decorator):
    def __init__(self):
        super().__init__("Mısır",2)

def print_menu():
    with open("Menu.txt", "r") as file:
        print(file.read())

def get_pizza_choice():
    pizza = None
    while pizza is None:
        choice = input("Lütfen bir pizza tabanı seçiniz: ")
        if choice == "1":
            pizza = Klasik()
        elif choice == "2":
            pizza = Margarita()
        elif choice == "3":
            pizza = TurkPizza()
        elif choice == "4":
            pizza = SadePizza()
        else:
            print("Geçersiz seçim, lütfen tekrar deneyin.")
    return pizza

def get_sauce_choice():
    sauce = None
    while sauce is None:
        choice = input("Lütfen bir sos seçiniz: ")
        if choice == "11":
            sauce = Zeytin()
        elif choice == "12":
            sauce = Mantar()
        elif choice == "13":
            sauce = KeciPeyniri()
        elif choice == "14":
            sauce = Et()
        elif choice == "15":
            sauce = Sogan()
        elif choice == "16":
            sauce = Misir()
        else:
            print("Geçersiz seçim, lütfen tekrar deneyin.")
    return sauce

with open('Orders_Database.csv', 'w') as creating_new_csv_file: 
   pass

from datetime import datetime

def main():
  print_menu()
  pizza = get_pizza_choice()
  sauce = get_sauce_choice()
  cost = pizza.get_cost() + sauce.get_cost()
  Name = input("Lütfen isminizi giriniz: ")
  id = input("Lütfen Lütfen TC Kimlik numaranızı giriniz: ")
  creditcardnumber = input("Lütfen kredi kartı numaranızı giriniz: ")
  creditcardpassword = input("Lütfen şifrenizi giriniz: ")
  now = datetime.now()
  with open('Orders_Database.csv', mode='a') as new: 
    new_writer = csv.writer(new, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    new_writer.writerow([Name, id, creditcardnumber, creditcardpassword, pizza.get_description(), sauce.get_description(), cost,now])



main()





